### ISSUE TITLE
Endpoint to get all todo items

### ISSUE THREAD

**Issue by Dhruv9449** [Dhruv9449/FastAPI-TODO#4]
# Endpoint to get all todo items
Create an endpoint in `FastAPI-TODO/app/routes.py` to fetch all the todo items stored in the database, sorted by the descending order of their creation.

**Comment by cmarchena** [comment]
This [PR](https://github.com/Dhruv9449/FastAPI-TODO/pull/10) creates the endpoint that gets all todo items
