### ISSUE TITLE
Endpoint to delete a todo item

### ISSUE THREAD

**Issue by Dhruv9449** [Dhruv9449/FastAPI-TODO#8]
# Endpoint to delete a todo item
Create an endpoint in `FastAPI-TODO/app/routes.py` to delete a given todo item.

**Comment by dhruvdabhi101** [comment]
I would like to work on this issue

**Comment by cmarchena** [comment]
Hello @Dhruv9449 could you please assign me this issue?
Thanks!

**Comment by Dhruv9449** [comment]
> Hello @Dhruv9449 could you please assign me this issue? Thanks!

Done :)

**Comment by Dhruv9449** [comment]
@cmarchena any updates?

**Comment by cmarchena** [comment]
Hi @Dhruv9449, yes. I have submitted a PR for your review. Please let me know any news about it

**Comment by Dhruv9449** [comment]
Sure let me check it out
